# Generated by Django 2.0.6 on 2018-09-14 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du projet')),
                ('date_creation', models.DateField(default=datetime.date.today, verbose_name='Date de création')),
                ('date_exe', models.DateField(blank=True, default=None, null=True, verbose_name='Date de démarrage des travaux')),
                ('annee_teamber', models.IntegerField(verbose_name='Année Teamber')),
                ('numero_teamber', models.IntegerField(verbose_name='Numéro Teamber')),
                ('nb_lots', models.IntegerField(default=0, verbose_name='Nombre de lots')),
                ('nb_etages', models.IntegerField(default=0, verbose_name="Nombre d'étages")),
                ('surf_sol', models.IntegerField(default=0, verbose_name='Surface au sol')),
                ('surf_shon', models.IntegerField(default=0, verbose_name='Surface SHON')),
                ('photo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Projet',
                'ordering': ['-annee_teamber', 'numero_teamber'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
    ]
