# Generated by Django 2.0.6 on 2018-09-21 14:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse1', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Adresse N°1 ')),
                ('adresse2', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Adresse N°2 ')),
                ('code_postal', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Code Postal ')),
                ('ville', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Ville ')),
                ('pays', models.CharField(blank=True, default='France', max_length=255, null=True, verbose_name='Pays ')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('numero_teamber', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Numéro Teamber ')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du projet ')),
                ('agence', models.CharField(blank=True, choices=[('Annecy', 'Annecy'), ('Lyon', 'Lyon')], default='Annecy', max_length=20, null=True, verbose_name='Agence interne')),
                ('photo', models.ImageField(blank=True, default='images/logo.jpg', null=True, upload_to='images/', verbose_name='Photo du projet (facultatif) ')),
                ('date_creation', models.DateField(default=datetime.date.today, verbose_name='Date de création ')),
                ('adresse', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='collaborateurs.Adresse')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-numero_teamber'],
            },
        ),
        migrations.CreateModel(
            name='PropProjet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_logements', models.IntegerField(blank=True, default=0, null=True, verbose_name='Nombre de logements ')),
                ('nb_etages', models.IntegerField(blank=True, default=0, null=True, verbose_name="Nombre d'étages ")),
                ('surf_sol', models.IntegerField(blank=True, default=0, null=True, verbose_name='Surface au sol (m²) ')),
                ('surf_shon', models.IntegerField(blank=True, default=0, null=True, verbose_name='Surface SHON (m²) ')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de rendu ')),
            ],
        ),
        migrations.AddField(
            model_name='projet',
            name='proprietes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='collaborateurs.PropProjet'),
        ),
    ]
