# Generated by Django 2.1.2 on 2018-12-03 11:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=255, verbose_name='Prénom ')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom ')),
                ('portable', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir exactement 10 chiffres et commencer par 0', regex='^0(?P<num>\\d{9})$')])),
                ('ligne_directe', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir exactement 10 chiffres et commencer par 0', regex='^0(?P<num>\\d{9})$')])),
                ('mail', models.EmailField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='agence',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='entreprise',
            options={'ordering': ['nom_ent']},
        ),
        migrations.AlterField(
            model_name='agence',
            name='mail_contact',
            field=models.EmailField(max_length=255),
        ),
        migrations.AddField(
            model_name='personne',
            name='agence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborateurs.Agence'),
        ),
    ]
