# Generated by Django 2.1.2 on 2018-12-17 10:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='type_contact',
            field=models.CharField(choices=[('clients', 'Client'), ('entreprises', 'Executant'), ('collaborateurs', 'Interne')], default='entreprises', max_length=255),
        ),
        migrations.AlterField(
            model_name='personne',
            name='date_inscription_personne',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 17, 10, 26, 16, 68432, tzinfo=utc), verbose_name="Date d'inscription "),
        ),
        migrations.AlterField(
            model_name='personne',
            name='mail',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
