# Generated by Django 2.0.6 on 2018-10-01 16:27

import collaborateurs.models
from django.db import migrations, models
import storage


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=storage.OverwriteStorage(), upload_to=collaborateurs.models.image_path, verbose_name='Photo du projet (facultatif) '),
        ),
    ]
