# Generated by Django 2.0.6 on 2018-09-21 15:08

from django.db import migrations, models
import storage


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='photo',
            field=models.ImageField(blank=True, default='images/logo.jpg', null=True, storage=storage.OverwriteStorage(), upload_to='images/', verbose_name='Photo du projet (facultatif) '),
        ),
    ]
