# Generated by Django 2.0.6 on 2018-10-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='suffixe',
            field=models.CharField(choices=[('', 'Aucun'), ('bis', 'Bis'), ('ter', 'Ter')], default='', max_length=5, verbose_name='Suffixe'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='numero',
            field=models.IntegerField(default=0, verbose_name='Numéro du lot '),
        ),
    ]
