# Generated by Django 2.0.6 on 2018-10-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomaineCompetence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence', models.CharField(blank=True, choices=[('Faca', 'Façades'), ('Elec', 'Electricité'), ('NR', 'Non renseigné')], default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SecteurGeographique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(blank=True, choices=[('rhone', 'Rhône'), ('ain', 'Ain'), ('haute savoie', 'Haute-Savoie'), ('isere', 'Isère'), ('autre', 'Autre'), ('NR', 'Non renseigné')], default='NR', max_length=255)),
                ('region', models.CharField(blank=True, choices=[('AUV-RN', 'Auvergne Rhône Alpes'), ('france', 'France entière'), ('autre', 'Autre'), ('NR', 'Non renseigné')], default='NR', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='documentagence',
            name='categorie',
            field=models.CharField(blank=True, choices=[('assurance', 'Assurance'), ('RC', 'Responsabilité civile'), ('autre', 'Autre')], default='autre', max_length=255, null=True, verbose_name='Catégorie de document'),
        ),
        migrations.RemoveField(
            model_name='lot',
            name='activites',
        ),
        migrations.AddField(
            model_name='lot',
            name='activites',
            field=models.ManyToManyField(to='collaborateurs.DomaineCompetence'),
        ),
    ]
