# Generated by Django 2.0.6 on 2018-10-17 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0002_auto_20181016_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='agence',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collaborateurs.Agence'),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='projet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collaborateurs.Projet'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='activites',
            field=models.ManyToManyField(blank=True, to='collaborateurs.DomaineCompetence'),
        ),
    ]
