# Generated by Django 2.1.2 on 2018-12-03 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0002_auto_20181203_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='date_inscription_personne',
            field=models.DateTimeField(default=datetime.date.today, verbose_name="Date d'inscription "),
        ),
    ]
