# Generated by Django 2.1.2 on 2018-12-14 17:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0002_auto_20181214_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeloffrelot',
            name='statut',
            field=models.CharField(blank=True, choices=[('Non créé', 'Non créé'), ('En création', 'En création'), ('Validé', 'Validé'), ('Envoyé', 'Envoyé')], default='Non créé', max_length=255),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='type_contact',
            field=models.CharField(choices=[('client', 'Client'), ('executant', 'Executant'), ('interne', 'Interne')], default='executant', max_length=255),
        ),
        migrations.AlterField(
            model_name='personne',
            name='date_inscription_personne',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 14, 17, 22, 58, 548977, tzinfo=utc), verbose_name="Date d'inscription "),
        ),
    ]
