# Generated by Django 2.1.2 on 2018-12-17 15:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0002_auto_20181217_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeloffre',
            name='statut',
            field=models.CharField(blank=True, choices=[('En création', 'En création'), ('Validé', 'Validé'), ('Envoyé', 'Envoyé')], default='En création', max_length=255),
        ),
        migrations.AlterField(
            model_name='personne',
            name='date_inscription_personne',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 17, 15, 4, 8, 433591, tzinfo=utc), verbose_name="Date d'inscription "),
        ),
    ]
