# Generated by Django 2.0.6 on 2018-09-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0002_auto_20180914_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
