# Generated by Django 2.0.6 on 2018-09-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0003_auto_20180914_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.ImageField(upload_to='')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
    ]
