# Generated by Django 2.0.6 on 2018-09-21 15:54

import collaborateurs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0003_auto_20180921_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='photo',
            field=models.ImageField(blank=True, default='images/logo.jpg', null=True, upload_to=collaborateurs.models.image_path, verbose_name='Photo du projet (facultatif) '),
        ),
    ]
