# Generated by Django 2.0.6 on 2018-10-17 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0003_auto_20181017_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domainecompetence',
            options={'ordering': ['competence']},
        ),
        migrations.AlterField(
            model_name='documentlot',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='collaborateurs.Lot'),
        ),
        migrations.AlterField(
            model_name='domainecompetence',
            name='competence',
            field=models.CharField(choices=[('Façades', 'Façades'), ('Electricité', 'Electricité'), ('Non renseigné', 'Non renseigné'), ('Autre', 'Autre'), ('Autre', 'Autre'), ('Autre', 'Autre'), ('Autre', 'Autre')], default='NR', max_length=255),
        ),
        migrations.AlterField(
            model_name='lot',
            name='numero',
            field=models.IntegerField(verbose_name='Numéro du lot '),
        ),
    ]
