# Generated by Django 2.1.2 on 2018-12-03 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0003_personne_date_inscription_personne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collaborateurs.Agence'),
        ),
    ]
