# Generated by Django 2.1.2 on 2018-12-03 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0004_auto_20181203_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agence',
            name='num_SIRET',
            field=models.CharField(max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro SIRET doit être composé de 13 chiffres exactement', regex='^(?P<siret>\\d{13})$')], verbose_name='N°SIRET'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='num_SIREN',
            field=models.CharField(max_length=9, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro SIREN doit être composé de 9 chiffres exactement ', regex='^(?P<siren>\\d{9})$')], verbose_name='N°SIREN (9 premiers chiffres du N°SIRET) '),
        ),
    ]
