# Generated by Django 2.0.6 on 2018-10-17 13:02

import collaborateurs.models
import datetime
from django.db import migrations, models
import storage


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0004_auto_20181017_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='logo_agence',
            field=models.ImageField(blank=True, null=True, storage=storage.OverwriteStorage(), upload_to=collaborateurs.models.fichier_agence_path, verbose_name='Photo du projet (facultatif) '),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='logo_ent',
            field=models.ImageField(blank=True, null=True, storage=storage.OverwriteStorage(), upload_to=collaborateurs.models.fichier_entreprise_path, verbose_name='Photo du projet (facultatif) '),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='date_inscription',
            field=models.DateTimeField(blank=True, default=datetime.date.today, verbose_name="Date d'inscription : "),
        ),
    ]
