# Generated by Django 2.0.6 on 2018-09-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0004_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='fichier',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
