# Generated by Django 2.0.6 on 2018-10-17 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0005_auto_20181017_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agence',
            old_name='date_creation',
            new_name='date_creation_agence',
        ),
        migrations.RenameField(
            model_name='agence',
            old_name='date_inscription',
            new_name='date_inscription_agence',
        ),
        migrations.AlterField(
            model_name='adresse',
            name='adresse1',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Adresse '),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='adresse2',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name="Complément d'adresse "),
        ),
        migrations.AlterField(
            model_name='agence',
            name='fax',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir 10 chiffres', regex='^0(?P<num>\\d{9})$')]),
        ),
        migrations.AlterField(
            model_name='agence',
            name='telephone',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir 10 chiffres', regex='^0(?P<num>\\d{9})$')]),
        ),
    ]
