# Generated by Django 2.1.2 on 2018-12-03 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0005_auto_20181203_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='date_inscription_personne',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 3, 17, 28, 12, 102918), verbose_name="Date d'inscription "),
        ),
    ]
