# Generated by Django 2.0.6 on 2018-09-14 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0005_auto_20180914_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='annee_teamber',
            field=models.IntegerField(verbose_name='Année Teamber * '),
        ),
        migrations.AlterField(
            model_name='projet',
            name='date_creation',
            field=models.DateField(default=datetime.date.today, verbose_name='Date de création * '),
        ),
        migrations.AlterField(
            model_name='projet',
            name='date_exe',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date de démarrage des travaux (facultatif) '),
        ),
        migrations.AlterField(
            model_name='projet',
            name='nb_etages',
            field=models.IntegerField(default=0, verbose_name="Nombre d'étages (facultatif) "),
        ),
        migrations.AlterField(
            model_name='projet',
            name='nb_lots',
            field=models.IntegerField(default=0, verbose_name='Nombre de lots (facultatif) '),
        ),
        migrations.AlterField(
            model_name='projet',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Nom du projet * '),
        ),
        migrations.AlterField(
            model_name='projet',
            name='numero_teamber',
            field=models.IntegerField(verbose_name='Numéro Teamber * '),
        ),
        migrations.AlterField(
            model_name='projet',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Logo du projet  (facultatif) '),
        ),
        migrations.AlterField(
            model_name='projet',
            name='surf_shon',
            field=models.IntegerField(default=0, verbose_name='Surface SHON (facultatif) '),
        ),
        migrations.AlterField(
            model_name='projet',
            name='surf_sol',
            field=models.IntegerField(default=0, verbose_name='Surface au sol (facultatif) '),
        ),
    ]
