# Generated by Django 2.0.6 on 2018-10-17 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0006_auto_20181017_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entreprise',
            old_name='date_creation',
            new_name='date_creation_ent',
        ),
        migrations.RenameField(
            model_name='entreprise',
            old_name='date_inscription',
            new_name='date_inscription_ent',
        ),
        migrations.RenameField(
            model_name='entreprise',
            old_name='nom',
            new_name='nom_ent',
        ),
    ]
