# Generated by Django 2.1.2 on 2018-12-05 17:04

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0006_auto_20181203_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agence',
            options={'ordering': ['-categorie', 'nom']},
        ),
        migrations.AlterField(
            model_name='agence',
            name='num_SIRET',
            field=models.CharField(max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro SIRET doit être composé de 14 chiffres', regex='^(?P<siret>\\d{14})$')], verbose_name='N°SIRET'),
        ),
        migrations.AlterField(
            model_name='domainecompetence',
            name='competence',
            field=models.CharField(choices=[('Façades', 'Façades'), ('Electricité', 'Electricité'), ('Non renseigné', 'Non renseigné'), ('Autre', 'Autre')], default='NR', max_length=255),
        ),
        migrations.AlterField(
            model_name='personne',
            name='date_inscription_personne',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 5, 17, 4, 12, 903638, tzinfo=utc), verbose_name="Date d'inscription "),
        ),
    ]
