# Generated by Django 2.0.6 on 2018-10-17 15:24

import collaborateurs.models
from django.db import migrations, models
import storage


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0007_auto_20181017_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agence',
            name='logo_agence',
            field=models.ImageField(blank=True, null=True, storage=storage.OverwriteStorage(), upload_to=collaborateurs.models.fichier_agence_path, verbose_name="Logo de l'agence si différent (facultatif) "),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='logo_ent',
            field=models.ImageField(blank=True, null=True, storage=storage.OverwriteStorage(), upload_to=collaborateurs.models.fichier_entreprise_path, verbose_name="Logo de l'entreprise (facultatif) "),
        ),
    ]
