# Generated by Django 2.1.2 on 2018-12-06 08:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0007_auto_20181205_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='date_inscription_personne',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 6, 8, 59, 29, 94637, tzinfo=utc), verbose_name="Date d'inscription "),
        ),
    ]
