# Generated by Django 2.0.6 on 2018-09-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0007_auto_20180917_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='photo',
            field=models.ImageField(blank=True, default='images/logo.jpg', null=True, upload_to='images/', verbose_name='Logo du projet  (facultatif) '),
        ),
    ]
