# Generated by Django 2.0.6 on 2018-09-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0008_auto_20180917_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projet',
            options={'ordering': ['-annee_teamber', '-numero_teamber'], 'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
        migrations.AddField(
            model_name='projet',
            name='numero_identifiant',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Identifiant Teamber : '),
        ),
    ]
