# Generated by Django 2.1.2 on 2018-12-06 16:48

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0009_auto_20181206_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeloffrelot',
            name='relance',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='personne',
            name='date_inscription_personne',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 6, 16, 48, 48, 114390, tzinfo=utc), verbose_name="Date d'inscription "),
        ),
    ]
