# Generated by Django 2.0.6 on 2018-10-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0009_auto_20181017_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='competences',
            field=models.ManyToManyField(blank=True, to='collaborateurs.DomaineCompetence'),
        ),
        migrations.AlterField(
            model_name='agence',
            name='lots',
            field=models.ManyToManyField(blank=True, related_name='repondants', to='collaborateurs.Lot'),
        ),
    ]
