# Generated by Django 2.0.6 on 2018-09-19 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0009_auto_20180919_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse1', models.CharField(default='NR', max_length=255, verbose_name='Adresse N°1 ')),
                ('adresse2', models.CharField(default='NR', max_length=255, verbose_name='Adresse N°2 ')),
                ('code_postal', models.CharField(default='NR', max_length=255, verbose_name='Code Postal ')),
                ('ville', models.CharField(default='NR', max_length=255, verbose_name='Ville ')),
                ('pays', models.CharField(default='France', max_length=255, verbose_name='Pays ')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AlterField(
            model_name='projet',
            name='numero_identifiant',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Identifiant Teamber '),
        ),
        migrations.AddField(
            model_name='projet',
            name='adresse',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='collaborateurs.Adresse'),
        ),
    ]
