# Generated by Django 2.0.6 on 2018-09-19 12:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0010_auto_20180919_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropProjet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_lots', models.IntegerField(default=0, verbose_name='Nombre de logements ')),
                ('nb_etages', models.IntegerField(default=0, verbose_name="Nombre d'étages ")),
                ('surf_sol', models.IntegerField(default=0, verbose_name='Surface au sol (m²) ')),
                ('surf_shon', models.IntegerField(default=0, verbose_name='Surface SHON (m²) ')),
                ('date_exe', models.DateField(blank=True, null=True, verbose_name='Date de démarrage des travaux ')),
            ],
        ),
        migrations.RemoveField(
            model_name='projet',
            name='date_exe',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='nb_etages',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='nb_lots',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='surf_shon',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='surf_sol',
        ),
        migrations.AlterField(
            model_name='projet',
            name='annee_teamber',
            field=models.IntegerField(verbose_name='Année Teamber '),
        ),
        migrations.AlterField(
            model_name='projet',
            name='date_creation',
            field=models.DateField(default=datetime.date.today, verbose_name='Date de création '),
        ),
        migrations.AlterField(
            model_name='projet',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Nom du projet '),
        ),
        migrations.AlterField(
            model_name='projet',
            name='numero_teamber',
            field=models.IntegerField(verbose_name='Numéro Teamber '),
        ),
        migrations.AlterField(
            model_name='projet',
            name='photo',
            field=models.ImageField(blank=True, default='images/logo.jpg', null=True, upload_to='images/', verbose_name='Photo du projet (facultatif) '),
        ),
        migrations.AddField(
            model_name='projet',
            name='proprietes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='collaborateurs.PropProjet'),
        ),
    ]
