# Generated by Django 2.0.6 on 2018-10-18 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0010_auto_20181018_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agence',
            old_name='competences',
            new_name='competences_agence',
        ),
    ]
