# Generated by Django 2.1.2 on 2018-12-06 17:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0010_auto_20181206_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeloffre',
            name='lots',
            field=models.ManyToManyField(blank=True, to='collaborateurs.Lot'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='date_inscription_personne',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 6, 17, 15, 43, 750625, tzinfo=utc), verbose_name="Date d'inscription "),
        ),
    ]
