# Generated by Django 2.1.2 on 2018-12-06 18:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0011_auto_20181206_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echeance',
            name='appel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='collaborateurs.AppelOffre'),
        ),
        migrations.AlterField(
            model_name='echeance',
            name='appelGlobal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='collaborateurs.AppelOffreGlobal'),
        ),
        migrations.AlterField(
            model_name='echeance',
            name='appelLot',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='collaborateurs.AppelOffreLot'),
        ),
        migrations.AlterField(
            model_name='echeance',
            name='projet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='collaborateurs.Projet'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='date_inscription_personne',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 6, 18, 27, 26, 154515, tzinfo=utc), verbose_name="Date d'inscription "),
        ),
    ]
