# Generated by Django 2.0.6 on 2018-09-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0011_auto_20180919_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='adresse1',
            field=models.CharField(default='', max_length=255, verbose_name='Adresse N°1 '),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='adresse2',
            field=models.CharField(default='', max_length=255, verbose_name='Adresse N°2 '),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='code_postal',
            field=models.CharField(default='', max_length=255, verbose_name='Code Postal '),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='ville',
            field=models.CharField(default='', max_length=255, verbose_name='Ville '),
        ),
    ]
