# Generated by Django 2.1.2 on 2018-12-07 09:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0012_auto_20181206_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='date_inscription_personne',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 7, 9, 52, 36, 192033, tzinfo=utc), verbose_name="Date d'inscription "),
        ),
    ]
