# Generated by Django 2.0.6 on 2018-10-18 12:14

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0012_auto_20181018_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agence',
            name='date_inscription_agence',
            field=models.DateTimeField(default=datetime.date.today, verbose_name="Date d'inscription "),
        ),
        migrations.AlterField(
            model_name='agence',
            name='nom',
            field=models.CharField(max_length=255, verbose_name="Dénomination de l'agence "),
        ),
        migrations.AlterField(
            model_name='agence',
            name='num_SIRET',
            field=models.CharField(max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Le numéro SIRET doit être composé de 13 chiffres exactement', regex='^(?P<siret>\\d{13})$')], verbose_name='N°SIRET'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='date_inscription_ent',
            field=models.DateTimeField(blank=True, default=datetime.date.today, verbose_name="Date d'inscription "),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='nom_ent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom de l'entreprise "),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='num_SIREN',
            field=models.CharField(max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='Le numéro SIREN doit être composé de 9 chiffres exactement ', regex='^(?P<siren>\\d{9})$')], verbose_name='N°SIREN (9 premiers chiffres du N°SIRET) '),
        ),
    ]
