# Generated by Django 2.0.6 on 2018-09-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0012_auto_20180919_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projet',
            options={'ordering': ['-numero_teamber'], 'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
        migrations.RemoveField(
            model_name='projet',
            name='annee_teamber',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='numero_identifiant',
        ),
        migrations.AlterField(
            model_name='projet',
            name='numero_teamber',
            field=models.CharField(max_length=255, verbose_name='Numéro Teamber '),
        ),
    ]
