# Generated by Django 2.0.6 on 2018-09-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0013_auto_20180919_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='id',
        ),
        migrations.AlterField(
            model_name='projet',
            name='numero_teamber',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Numéro Teamber '),
        ),
    ]
