# Generated by Django 2.1.2 on 2018-12-07 09:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0013_auto_20181207_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeloffre',
            name='numero',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personne',
            name='date_inscription_personne',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 7, 9, 56, 26, 205942, tzinfo=utc), verbose_name="Date d'inscription "),
        ),
    ]
