# Generated by Django 2.1.2 on 2018-12-10 12:11

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0014_auto_20181207_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeloffrelot',
            name='relance',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='Intervalle de relance (jours calendaires)'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='projet',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='collaborateurs.Projet'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='date_inscription_personne',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 12, 11, 12, 559011, tzinfo=utc), verbose_name="Date d'inscription "),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='architecture',
            field=models.CharField(blank=True, choices=[('Basique', 'Basique'), ('Moyenne', 'Moyenne'), ('Complexe', 'Complexe')], max_length=255, null=True, verbose_name="Type d'architecture "),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='secteur',
            field=models.CharField(blank=True, choices=[('Copropriété', 'Copropriété'), ('Tertiaire', 'Tertiaire'), ('Social', 'Social'), ('Individuel', 'Individuel')], max_length=255, null=True, verbose_name='Catégorie de clientèle '),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='travaux',
            field=models.CharField(blank=True, choices=[('Rénovation', 'Rénovation'), ('Sinistre', 'Sinistre'), ('Neuf', 'Neuf')], max_length=255, null=True, verbose_name='Type de travaux'),
        ),
    ]
