# Generated by Django 2.0.6 on 2018-09-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0015_projet_agence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propprojet',
            old_name='nb_lots',
            new_name='nb_logements',
        ),
        migrations.RemoveField(
            model_name='propprojet',
            name='date_exe',
        ),
        migrations.AddField(
            model_name='propprojet',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de rendu '),
        ),
    ]
