# Generated by Django 2.1.2 on 2018-12-10 12:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0015_auto_20181210_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collaborateurs.Projet'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='date_inscription_personne',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 12, 22, 44, 803103, tzinfo=utc), verbose_name="Date d'inscription "),
        ),
    ]
