# Generated by Django 2.1.2 on 2018-12-11 10:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0016_auto_20181210_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeloffrelot',
            name='date_de_creation',
            field=models.DateField(default=datetime.date.today, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='date_inscription_personne',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 10, 2, 33, 285560, tzinfo=utc), verbose_name="Date d'inscription "),
        ),
    ]
