# Generated by Django 2.0.6 on 2018-09-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0016_auto_20180920_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='adresse1',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Adresse N°1 '),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='adresse2',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Adresse N°2 '),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='code_postal',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Code Postal '),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='pays',
            field=models.CharField(blank=True, default='France', max_length=255, null=True, verbose_name='Pays '),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='ville',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Ville '),
        ),
        migrations.AlterField(
            model_name='propprojet',
            name='nb_etages',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="Nombre d'étages "),
        ),
        migrations.AlterField(
            model_name='propprojet',
            name='nb_logements',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Nombre de logements '),
        ),
        migrations.AlterField(
            model_name='propprojet',
            name='surf_shon',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Surface SHON (m²) '),
        ),
        migrations.AlterField(
            model_name='propprojet',
            name='surf_sol',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Surface au sol (m²) '),
        ),
    ]
