# Generated by Django 2.1.2 on 2018-12-11 10:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0017_auto_20181211_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeloffrelot',
            name='date_lancement',
        ),
        migrations.AlterField(
            model_name='personne',
            name='date_inscription_personne',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 10, 4, 4, 743311, tzinfo=utc), verbose_name="Date d'inscription "),
        ),
    ]
