# Generated by Django 2.1.2 on 2018-12-11 10:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0018_auto_20181211_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='date_inscription_personne',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 10, 7, 5, 667923, tzinfo=utc), verbose_name="Date d'inscription "),
        ),
    ]
