# Generated by Django 2.1.2 on 2018-12-11 10:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0019_auto_20181211_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeloffrelot',
            name='date_lancement',
            field=models.DateField(default=datetime.date.today, verbose_name='Date de démarrage de la consultation'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='date_inscription_personne',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 10, 7, 16, 231529, tzinfo=utc), verbose_name="Date d'inscription "),
        ),
    ]
