# Generated by Django 2.1.2 on 2018-12-11 10:34

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0020_auto_20181211_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeloffrelot',
            name='date_de_creation',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='appeloffrelot',
            name='relance',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Intervalle de relance (jours calendaires)'),
        ),
        migrations.AlterField(
            model_name='echeance',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date de fin de la consultation'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='date_inscription_personne',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 10, 34, 6, 733027, tzinfo=utc), verbose_name="Date d'inscription "),
        ),
    ]
