# Generated by Django 2.1.2 on 2018-12-11 15:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0022_auto_20181211_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='type_contact',
            field=models.CharField(choices=[('client', 'Client'), ('executant', 'Executant')], default='executant', max_length=255),
        ),
        migrations.AlterField(
            model_name='personne',
            name='date_inscription_personne',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 15, 8, 43, 88990, tzinfo=utc), verbose_name="Date d'inscription "),
        ),
    ]
