# Generated by Django 2.1.2 on 2018-12-12 16:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0023_auto_20181211_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='AO',
        ),
        migrations.RemoveField(
            model_name='offre',
            name='agence',
        ),
        migrations.RemoveField(
            model_name='offre',
            name='personne',
        ),
        migrations.AlterField(
            model_name='personne',
            name='date_inscription_personne',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 12, 16, 52, 6, 113336, tzinfo=utc), verbose_name="Date d'inscription "),
        ),
        migrations.DeleteModel(
            name='Offre',
        ),
    ]
