# Generated by Django 2.1.2 on 2018-12-17 09:17

from django.db import migrations, models
import django.db.models.deletion
import entreprises.models
import storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collaborateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentOffreLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(blank=True, null=True, storage=storage.OverwriteStorage(), upload_to=entreprises.models.fichier_offre_path, verbose_name="Document de l'offre : ")),
                ('categorie', models.CharField(blank=True, choices=[('DPGF', 'DPGF'), ('CCTP', 'CCTP'), ('AE', "Acte d'engagement"), ('AUTRE', 'Autre')], default='AUTRE', max_length=255, null=True, verbose_name='Catégorie de document')),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(blank=True, choices=[('Non commencé', 'Non commencé'), ('En cours', 'En cours'), ('Terminé', 'Terminé')], default='Non commencé', max_length=255, verbose_name="Statut de l'offre")),
                ('appel_lot', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='collaborateurs.AppelOffreLot')),
                ('lot', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='collaborateurs.Lot')),
                ('personne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='collaborateurs.Personne')),
            ],
        ),
        migrations.AddField(
            model_name='documentoffrelot',
            name='offre',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='entreprises.Offre'),
        ),
    ]
